#!/bin/bash
#
# record with noise gate
#
#sox -t alsa default  $FILE.wav silence 1 0.1 5% 1 1.0 5%

echo "Name your file, eg. noise:"
read name

FILE=$name.$(date "+%F").wav

echo "Recording starts when silence is interrupted. Shuts down on silence restored."
echo "Write to file:"
echo $FILE
sox -t alsa default  $FILE silence 1 0.1 3% 1 1.0 3%
